# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches }: let
  src = fetchFromGitHub {
    owner = "glitch-soc";
    repo = "mastodon";
    rev = "bb98d970e3f3333f85d454bc1fd26a1b582b14d2";
    hash = "sha256-DW6OmMKKx44vicslp6iPVD9ntLYk/8GDjshYZTVqE2g=";
  };
in applyPatches {
  inherit src;
  patches = [];
}
